spring:
  datasource:
    url: jdbc:mysql://47.96.159.71/oomall?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    username: oomall
    password: oomallp@$$w0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8090
