pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  helper-dialect: mysql

spring:
  datasource:
    url: jdbc:mysql://47.96.159.71:3306/oomall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: oomall
    password: oomallp@$$w0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  application:
    name: topicService
server:
  port: 8830

mybatis:
  type-aliases-package: com.tardybird.topic.po
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://47.96.159.71:8888/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 47.96.159.71
    non-secure-port: 8830