##########################################################################
# PCW
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  helper-dialect: mysql

spring:
  datasource:
    hikari:
      maximum-pool-size: 10
    url: jdbc:mysql://47.52.88.176/DB3_8?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    username: user3_8
    password: ooad8
  application:
    name: topicService
server:
  port: 8830

mybatis:
  type-aliases-package: com.tardybird.topic.po
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://47.96.159.71:8888/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 47.96.159.71
    non-secure-port: 8830


##########################################################################
# KLY
#pagehelper:
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql
#  helper-dialect: mysql
#
#spring:
#  datasource:
#    hikari:
#      maximum-pool-size: 10
#    url: jdbc:mysql://148.70.28.112/wowomall?useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: wowoto
#    password: zqhlovekly
#  application:
#    name: topicService
#server:
#  port: 8831
#
#mybatis:
#  type-aliases-package: com.tardybird.topic.po
#  mapper-locations: classpath:mapper/*.xml
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://148.70.28.112:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    ip-address: 121.199.2.219
#    non-secure-port: 8831



##########################################################################
# JQS
#pagehelper:
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql
#  helper-dialect: mysql
#
#spring:
#  datasource:
#    hikari:
#      maximum-pool-size: 10
#    url: jdbc:mysql://47.52.88.176/DB3_8?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
#    username: user3_8
#    password: ooad8
#  application:
#    name: topicService
#server:
#  port: 8832
#
#mybatis:
#  type-aliases-package: com.tardybird.topic.po
#  mapper-locations: classpath:mapper/*.xml
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://112.124.5.149:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    ip-address: 121.199.2.219
#    non-secure-port: 8832



##########################################################################
# ZTY
#pagehelper:
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql
#  helper-dialect: mysql
#
#spring:
#  datasource:
#    hikari:
#      maximum-pool-size: 10
#    url: jdbc:mysql://47.52.88.176/DB3_8?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
#    username: user3_8
#    password: ooad8
#  application:
#    name: topicService
#server:
#  port: 8833
#
#mybatis:
#  type-aliases-package: com.tardybird.topic.po
#  mapper-locations: classpath:mapper/*.xml
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://47.100.32.48:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    ip-address: 121.199.2.219
#    non-secure-port: 8833